### ISSUE TITLE
Migrate next.js deliveroo to 3.0.0-beta.5 results in error in order.js

### ISSUE THREAD

**Issue by kktam** [strapi/strapi-examples#109]
**Node.js version**: v10.13.0

**npm version**: 6.9.0

**Strapi version**:   3.0.0-beta.5

**Operating system**: Windows 10 professional

**Which example is causing problem?** [https://github.com/strapi/strapi-examples/tree/master/nextjs-react-strapi-deliveroo-clone-tutorial](https://github.com/strapi/strapi-examples/tree/master/nextjs-react-strapi-deliveroo-clone-tutorial)

**Do you want to request a *feature* or report a *bug*?** Bug

**What is the current behavior?**
Migration to 3.0.0-beta.5 for next.js deliveroo example using the information from [https://strapi.io/documentation/3.0.0-beta.x/migration-guide/migration-guide-alpha.26-to-beta.html](https://strapi.io/documentation/3.0.0-beta.x/migration-guide/migration-guide-alpha.26-to-beta.html)

After migrating the code, the command 'strapi develop' results in the following error:

```
strapi develop
Building your admin UI with development configuration ...

√ Webpack
  Compiled successfully in 1.23m

[2019-06-17T12:48:36.447Z] error Something went wrong in the model `Order` with the attribute `user`
[2019-06-17T12:48:36.450Z] error TypeError: Cannot read property 'hasOwnProperty' of undefined
    at Object.getNature (C:\Users\n\code\strapi\deliveroobackend\node_modules\strapi-utils\lib\models.js:186:21)
    at _.forEach (C:\Users\n\code\strapi\deliveroobackend\node_modules\strapi-hook-bookshelf\lib\index.js:536:33)
    at C:\Users\n\code\strapi\deliveroobackend\node_modules\lodash\lodash.js:4911:15
    at baseForOwn (C:\Users\n\code\strapi\deliveroobackend\node_modules\lodash\lodash.js:2996:24)
    at C:\Users\n\code\strapi\deliveroobackend\node_modules\lodash\lodash.js:4880:18
    at Function.forEach (C:\Users\n\code\strapi\deliveroobackend\node_modules\lodash\lodash.js:9344:14)
    at _.forEach (C:\Users\n\code\strapi\deliveroobackend\node_modules\strapi-hook-bookshelf\lib\index.js:533:17)
    at C:\Users\n\code\strapi\deliveroobackend\node_modules\lodash\lodash.js:4911:15
    at baseForOwn (C:\Users\n\code\strapi\deliveroobackend\node_modules\lodash\lodash.js:2996:24)
    at C:\Users\n\code\strapi\deliveroobackend\node_modules\lodash\lodash.js:4880:18
    at Function.forEach (C:\Users\n\code\strapi\deliveroobackend\node_modules\lodash\lodash.js:9344:14)
    at mountModels (C:\Users\n\code\strapi\deliveroobackend\node_modules\strapi-hook-bookshelf\lib\index.js:99:15)
    at _.forEach (C:\Users\n\code\strapi\deliveroobackend\node_modules\strapi-hook-bookshelf\lib\index.js:867:11)
    at C:\Users\n\code\strapi\deliveroobackend\node_modules\lodash\lodash.js:4911:15
    at baseForOwn (C:\Users\n\code\strapi\deliveroobackend\node_modules\lodash\lodash.js:2996:24)
    at C:\Users\n\code\strapi\deliveroobackend\node_modules\lodash\lodash.js:4880:18
    at Function.forEach (C:\Users\n\code\strapi\deliveroobackend\node_modules\lodash\lodash.js:9344:14)
    at Function.initialize (C:\Users\ntam\code\strapi\deliveroobackend\node_modules\strapi-hook-bookshelf\lib\index.js:69:11)
    at C:\Users\n\code\strapi\deliveroobackend\node_modules\strapi\lib\hooks\index.js:52:31
    at after (C:\Users\n\code\strapi\deliveroobackend\node_modules\strapi\lib\hooks\index.js:153:39)
    at C:\Users\n\code\strapi\deliveroobackend\node_modules\lodash\lodash.js:9999:23
    at Strapi.once (C:\Users\n\code\strapi\deliveroobackend\node_modules\strapi\lib\hooks\index.js:164:17)
```

**If the current behavior is a bug, please provide the steps to reproduce the problem**
Steps as described in [https://strapi.io/documentation/3.0.0-beta.x/migration-guide/migration-guide-alpha.26-to-beta.html](https://strapi.io/documentation/3.0.0-beta.x/migration-guide/migration-guide-alpha.26-to-beta.html)

**What is the expected behavior?**  compile success.

**Comment by kktam** [comment]
I recheck the reproduce steps and found that the project dependencies does not work with npm but only with yarn.

after rebuilding Next.js deliveroo example I got a lesser but different React error. I am not sure if it is related to fact that the host is now installed with Strapi beta (npm install strapi@beta -g)

Here is new error message after starting client with 'yarn, yarn dev'

```
[ wait ]  compiling ...
Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
    in MyApp
    in Context.Provider
    in ApolloProvider
    in RenderPromisesProvider
TypeError: Cannot read property 'pathname' of undefined
    at Object.makePublicRouterInstance (C:\Users\ntam\code\strapi\deliveroo\node_modules\next\dist\client\router.js:148:23)
    at MyApp.getChildContext (C:\Users\ntam\code\strapi\deliveroo\.next\server\static\development\pages\_app.js:1925:26)
    at processChild (C:\Users\ntam\code\strapi\deliveroo\node_modules\react-dom\cjs\react-dom-server.node.development.js:2974:29)
    at resolve (C:\Users\ntam\code\strapi\deliveroo\node_modules\react-dom\cjs\react-dom-server.node.development.js:2812:5)
    at ReactDOMServerRenderer.render (C:\Users\ntam\code\strapi\deliveroo\node_modules\react-dom\cjs\react-dom-server.node.development.js:3202:22)
    at ReactDOMServerRenderer.read (C:\Users\ntam\code\strapi\deliveroo\node_modules\react-dom\cjs\react-dom-server.node.development.js:3161:29)
    at renderToStaticMarkup (C:\Users\ntam\code\strapi\deliveroo\node_modules\react-dom\cjs\react-dom-server.node.development.js:3661:27)
    at process (C:\Users\ntam\code\strapi\deliveroo\node_modules\react-apollo\react-apollo.cjs.js:1044:20)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[ event ] disposing inactive page(s): /next/dist/pages/_error
```

**Comment by lauriejim** [comment]
I haven't been able to reproduce.
I close this issue, let me know if you have other info.
