### ISSUE TITLE
Any support available on oracle db connect?

### ISSUE THREAD

**Issue by sabaruddin** [strapi/strapi-examples#14]

**Comment by lauriejim** [comment]
Actually no and it's not plan today.

**Comment by DVIMultimedia** [comment]
Not planned in 2020 ?

**Comment by achmedsgit** [comment]
please add support for oracle.

**Comment by stevefan1999-personal** [comment]
Technically speaking, this is not the concern of Strapi. Bookshelf relies on Knex, and Knex does support Oracle. However, you will have to be a little bit creative.

First, you will have to install the Oracle Client:
```bash
# yarn add oracledb
```
Then, you will have to patch `node_modules\strapi-connector-bookshelf\lib\knex.js`:
```patch
*** knex.js     2020-09-18 19:04:57.901164900 +0800
--- "knex copy.js"      2020-09-18 19:06:01.012209000 +0800
***************
*** 19,26 ****
    'mysql2',
    'sqlite3',
    'mariasql',
!   'oracle',
!   'strong-oracle',
    'mssql',
  ];

--- 19,25 ----
    'mysql2',
    'sqlite3',
    'mariasql',
!   'oracledb',
    'mssql',
  ];

***************
*** 98,103 ****
--- 97,103 ----
              ssl: _.get(connection.settings, 'ssl', false),
              timezone: _.get(connection.settings, 'timezone', 'utc'),
              filename: _.get(connection.settings, 'filename', '.tmp/data.db'),
+             connectString: _.get(connection.settings, 'host'),
            },
            ...connection.options,
            debug: _.get(connection.options, 'debug', false),
```
But consider that the CTO of Strapi, aka @lauriejim, was so pissed about adding Oracle support, so I assume he had some beef with Oracle before. Based on that, I doubt even if I tried to submit a PR he will immediately close it anyway.

If you do not want to modify the source code manually everytime, you can also 1. map oracledb dependency to oracle using symlink or 2. make a postinstall script to patch it automatically. If you go approach 1, make sure to not use the settings under connector but instead do it like this:
```js
module.exports = ({ env }) => ({
  defaultConnection: "default",
  connections: {
    default: {
      connector: "bookshelf",
      settings: {
        client: "oracle" // ONLY IF you use the dependency swapping/symlink method
      },
      options: {
        useNullAsDefault: true,
        connection: {
          user: "admin",
          password: "attack at dawn",
          host: "db202008101919_high",
        },
      },
    },
  },
});
```
This will unfortunately override all connection settings.

But even after that you will still be blocked: You are going to face this
```js
[2020-09-18T10:58:12.579Z] debug ⛔️ Server wasn't able to start properly.
[2020-09-18T10:58:12.580Z] error Error: Undefined binding(s) detected when compiling SELECT. Undefined column(s): [core_store.id] query: select * from (select "core_store".* from "core_store" where "core_store"."key" = ? and "core_store"."type" = ? and "core_store"."value" = ? and "core_store"."id" = ?) where rownum <= ?
    at Oracledb_Compiler.toSQL (E:\strapi\my-project\node_modules\knex\lib\query\compiler.js:101:13)
    at Builder.toSQL (E:\strapi\my-project\node_modules\knex\lib\query\builder.js:76:44)
    at E:\strapi\my-project\node_modules\knex\lib\runner.js:30:36
From previous event:
    at Runner.run (E:\strapi\my-project\node_modules\knex\lib\runner.js:25:16)
    at Builder.Target.then (E:\strapi\my-project\node_modules\knex\lib\interface.js:14:43)
    at processImmediate (internal/timers.js:456:21)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
I don't know what it is and I will update the status if me/you could make a breakthough.

**Comment by maulik-modi** [comment]
> Actually no and it's not plan today.

@lauriejim , Do you accept PR for oracle support. Some organizations are heavily invested and may not switch to another database system with failover, replication and all that stuff just to have CMS.

**Comment by dnikomon** [comment]
@stevefan1999-personal , @maulik-modi 

You can't put a CLOB in the WHERE clause. From the [documentation](https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/Comparison-Conditions.html#GUID-828576BF-E606-4EA6-B94B-BFF48B67F927):

> Large objects (LOBs) are not supported in comparison conditions. However, you can use PL/SQL programs for comparisons on CLOB data.

`"value" clob null` 

`where "core_store"."key" = :1 and "core_store"."type" = :2 and "core_store"."value" = :3`
