### ISSUE TITLE
Installing dependencies for login-react causes problems

### ISSUE THREAD

**Issue by s1710307070** [strapi/strapi-examples#158]
**Node.js version**: v12.14.1

**npm version**: 6.14.5

**Strapi version**: latest

**Operating system**: Windows 10 (Build 19041.264)

Running npm install for the project login-react causes issues:

```ngrok - downloading binary https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip ...
ngrok - binary downloaded...
ngrok - error unpacking binary Error: You cannot extract a file outside of the target path
    at C:\Users\david.kastner\source\repos\prototyp_website_strapi\strapi-examples\login-react\react-login-front-end-app\node_modules\decompress-zip\lib\decompress-zip.js:95:21
    at Array.map (<anonymous>)
    at C:\Users\david.kastner\source\repos\prototyp_website_strapi\strapi-examples\login-react\react-login-front-end-app\node_modules\decompress-zip\lib\decompress-zip.js:91:25
    at _fulfilled (C:\Users\david.kastner\source\repos\prototyp_website_strapi\strapi-examples\login-react\react-login-front-end-app\node_modules\q\q.js:854:54)
    at C:\Users\david.kastner\source\repos\prototyp_website_strapi\strapi-examples\login-react\react-login-front-end-app\node_modules\q\q.js:883:30
    at Promise.promise.promiseDispatch (C:\Users\david.kastner\source\repos\prototyp_website_strapi\strapi-examples\login-react\react-login-front-end-app\node_modules\q\q.js:816:13)
    at C:\Users\david.kastner\source\repos\prototyp_website_strapi\strapi-examples\login-react\react-login-front-end-app\node_modules\q\q.js:624:44
    at runSingle (C:\Users\david.kastner\source\repos\prototyp_website_strapi\strapi-examples\login-react\react-login-front-end-app\node_modules\q\q.js:137:13)
    at flush (C:\Users\david.kastner\source\repos\prototyp_website_strapi\strapi-examples\login-react\react-login-front-end-app\node_modules\q\q.js:125:13)
    at processTicksAndRejections (internal/process/task_queues.js:76:11)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules\watchpack\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN react-boilerplate@ No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ngrok@2.2.9 postinstall: `node ./postinstall.js`
npm ERR! Exit status 1```

**Comment by alexon1234** [comment]
https://github.com/strapi/strapi-examples/pull/149/files
