### ISSUE TITLE
Cant create new project

### ISSUE THREAD

**Issue by lddd** [strapi/strapi-examples#21]
Whats the problem here, i get the following error message after installting node js and strapi

```
~$ strapi new myProject

/usr/local/lib/node_modules/strapi/bin/strapi.js:10
const _ = require('lodash');
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:437:25)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.runMain (module.js:492:10)
    at process.startup.processNextTick.process._tickCallback (node.js:244:9)
```

**Comment by soupette** [comment]
What is your node and npm versions?

**Comment by lddd** [comment]
Solved, thanks.
