### ISSUE TITLE
I am getting these errors on npm start for cheesecakes

### ISSUE THREAD

**Issue by selotoprak** [strapi/strapi-examples#5]
ERROR (1611 on s-MacBook-Pro.local): Cannot find module 'sendmail'
    Error: Cannot find module 'sendmail'
        at Function.Module._resolveFilename (module.js:538:15)
        at Function.Module._load (module.js:468:25)
        at Module.require (module.js:587:17)
        at require (internal/module.js:11:18)
        at Object.<anonymous> (/Users/s/Desktop/strapi/strapi-examples/cheesecakes/plugins/email/services/Email.js:10:18)
        at Module._compile (module.js:643:30)
        at Object.Module._extensions..js (module.js:654:10)
        at Module.load (module.js:556:32)
        at tryModuleLoad (module.js:499:12)
        at Function.Module._load (module.js:491:3)
ERROR (1611 on s-MacBook-Pro.local): Cannot find module 'jsonwebtoken'
    Error: Cannot find module 'jsonwebtoken'
        at Function.Module._resolveFilename (module.js:538:15)
        at Function.Module._load (module.js:468:25)
        at Module.require (module.js:587:17)
        at require (internal/module.js:11:18)
        at Object.<anonymous> (/Users/s/Desktop/strapi/strapi-examples/cheesecakes/plugins/users-permissions/services/Jwt.js:10:13)
        at Module._compile (module.js:643:30)
        at Object.Module._extensions..js (module.js:654:10)
        at Module.load (module.js:556:32)
        at tryModuleLoad (module.js:499:12)
        at Function.Module._load (module.js:491:3)
ERROR (1611 on s-MacBook-Pro.local): Cannot find module 'bcryptjs'
    Error: Cannot find module 'bcryptjs'
        at Function.Module._resolveFilename (module.js:538:15)
        at Function.Module._load (module.js:468:25)
        at Module.require (module.js:587:17)
        at require (internal/module.js:11:18)
        at Object.<anonymous> (/Users/s/Desktop/strapi/strapi-examples/cheesecakes/plugins/users-permissions/services/User.js:11:16)
        at Module._compile (module.js:643:30)
        at Object.Module._extensions..js (module.js:654:10)
        at Module.load (module.js:556:32)
        at tryModuleLoad (module.js:499:12)
        at Function.Module._load (module.js:491:3)
(node:1611) DeprecationWarning: Mongoose: mpromise (mongoose's default promise library) is deprecated, plug in your own promise library instead: http://mongoosejs.com/docs/promises.html

**Comment by lauriejim** [comment]
Hello @selotoprak thank you for this issue.

The post install script is missing in the package.json to install plugins node modules. It's why you have this missing node module.

I have update the strapi version `alpha.7.3` to `alpha.8` (https://github.com/strapi/strapi-examples/pull/7) and it fix it.

Can you try again and tell me if it's OK ?
