### ISSUE TITLE
Error: Cannot find module '../utils/Manager.js'

### ISSUE THREAD

**Issue by odomojuli** [strapi/strapi-examples#53]
**Node.js version**: v10.1.0

**npm version**: npm@6.4.1

**Strapi version**: 3.0.0-alpha.14.1.1

**Operating system**: macOS 10.13.6 (17G65)

**Which example is causing problem?**: Deliveroo Tutorial

**What is the current behavior?**
```
> server@0.1.0 start /Users/odomojuli/Documents/GitHub/RN_PROTOTYPE/server
> node server.js

internal/modules/cjs/loader.js:573
    throw err;
    ^

Error: Cannot find module '../utils/Manager.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:571:15)
    at Function.Module._load (internal/modules/cjs/loader.js:497:25)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/odomojuli/Documents/GitHub/RN_PROTOTYPE/server/plugins/content-type-builder/services/ContentTypeBuilder.js:8:17)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! server@0.1.0 start: `node server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the server@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

```

**Comment by lauriejim** [comment]
You are talking about next or nuxt Deliveroo Tutorial ?

**Comment by nikri** [comment]
It's Nuxt that's missing the whole directory ../utils/

**Comment by lauriejim** [comment]
Thank you for reporting this issue. We are currently on another feature and bug fix. Since time is lacking on our side, feel free investigate and submit a PR, we’ll appreciate your contribution on this issue!
