### ISSUE TITLE
cheese cake example - Cannot read property 'policy' of null

### ISSUE THREAD

**Issue by sinanerdem** [strapi/strapi-examples#57]
**Node.js version**:
10.10.0
**npm version**:
6.4.1
**Strapi version**:
3.0.0-alpha.14.4.0
**Operating system**:
osx

**Which example is causing problem?**
cheesecakes
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
i installed and started the server with npm start. when i go to localhost:1337, it is empty. Error message is:
[2018-11-07T15:58:36.693Z] debug GET index.html (19 ms)
[2018-11-07T15:58:36.766Z] debug GET /scripts/index.js (4 ms)
TypeError: Cannot read property 'policy' of null
    at module.exports (/Users/erdesina/node/strapi-examples/cheesecakes/plugins/users-permissions/config/policies/permissions.js:50:18)
[2018-11-07T15:58:38.355Z] debug GET /cake/count (14 ms)
TypeError: Cannot read property 'policy' of null
    at module.exports (/Users/erdesina/node/strapi-examples/cheesecakes/plugins/users-permissions/config/policies/permissions.js:50:18)
[2018-11-07T15:58:38.359Z] debug GET /info (15 ms)
TypeError: Cannot read property 'policy' of null
    at module.exports (/Users/erdesina/node/strapi-examples/cheesecakes/plugins/users-permissions/config/policies/permissions.js:50:18)
[2018-11-07T15:58:38.367Z] debug GET /cake?_sort=id&_start=0&_limit=3 (19 ms)

I tried:
db['users-permissions_permission'].updateMany({}, {$set: {enabled: true}})

Didnt help.

**Comment by sinanerdem** [comment]
Correction:

```
use cheesecakes
db['users-permissions_permission'].updateMany({}, {$set: {enabled: true}})
```

inside mongo shell solved the problem.

**Comment by lauriejim** [comment]
I tried with fresh new install and db and it works well on my side.
